import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {ReactNode} from 'react';
import { DashboardWrapper } from "@/components/layout";
const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "ED Stock",
  description: "Generated by create next app",
};

const RootLayout=({
  children,
}: Readonly<{
  children: ReactNode;
}>)=> {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DashboardWrapper>
        {children}
        </DashboardWrapper>
        </body>
    </html>
  );
}
export default RootLayout;